### ISSUE TITLE
How to Sign In as another User?

### ISSUE THREAD

**Issue by KKamesh** [vmurin/react-native-azure-auth-sample#1]
I am using the react-native-azure-auth module and I am able to Sign In to Azure AD and Sign Out also works fine. However If I click "Sign In" again, I am directly getting logged-in as previously signed-in user without asking for credentials. Is there any way to implement this using the module? Thanks.

**Comment by vmurin** [comment]
I suppose you are testing the android version. 
There is a difference in logout behavior for iOS and Android due to restriction how you can control browser/web activity on android (it can not be closed automatically on load), so the identity provider (Azure in our case) session is really cleared only on iOS!
On Andriod you will be faced  with described behavior - on the repeated login the browser/web activity is started and as the user session is not expired yet the activity returns immediately with valid tokens.

 You can check the related code here:

https://github.com/vmurin/react-native-azure-auth/blob/73cb22d495de5409101877647e9590572092da07/src/webauth/index.js#L116

I will be glad if you can propose the solution how to clear ID-provider session on Android.
